### ISSUE TITLE
Generate translation percentage for language instead of resource

### ISSUE THREAD

**Issue by strophy** [greatislander/tenpercent#2]
I suspect the Transifex API doesn't support this, but I would like to generate translations statistics on a per-language for all resources basis, rather than per-resource for all languages. Is this currently possible, or should I request this from Transifex?

**Comment by greatislander** [comment]
@strophy To be honest, I didn't look into this — it might be possible. I will see what I can found out and let you know.

**Comment by niccokunzmann** [comment]
There is a progress report for languages https://docs.transifex.com/tracking/progress-reports

**Comment by strophy** [comment]
Is this information also available over the API?

**Comment by niccokunzmann** [comment]
@strophy I do not understand which API you mean. Certainly the informatrion it is available through the Transifex API.
Then, there is the index file https://github.com/greatislander/tenpercent/blob/master/index.js serving one endpoint.

**Comment by strophy** [comment]
My original reason for opening this issue was that the Transifex API cannot provide translation statistics on a per-language for all resources basis, rather than per-resource for all languages. I want to show translation progress for each language of a multi-file project. To my knowledge, this endpoint does not exist and must be calculated by a third-party project such as this one...

**Comment by greatislander** [comment]
@strophy I've finally taken a stab at this in #13. You can test it out on the preview deploy for that pull request:

https://tenpercent-git-feat-language-percentage.greatislander.vercel.app/?organization=pressbooks&project=pressbooks&language=ca

That link, for example, will return the translated percentage for Catalan for all resources in the Pressbooks project.
